name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MINECRAFT_VERSION: 26.1
  JAVA_VERSION: 25
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "microsoft"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew clean build -Pmod_version="${SHORT_SHA}"
      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: litehud-${{ env.SHORT_SHA }}
          path: build/libs/litehud-*[0-9].jar
