name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  MINECRAFT_VERSION: 26.1
  JAVA_VERSION: 25
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "microsoft"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build -Pmod_version="${GITHUB_REF_NAME#v}"
      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: litehud-${{ github.ref_name }}
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          generate_release_notes: true
          body: |
            Also available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/litehud)
          files: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659 # v3.3.0
        with:
          curseforge-id: ${{ secrets.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: build/libs/litehud-*[0-9].jar
